# Generated by Django 3.2 on 2021-07-31 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('no_of_students', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_per_student', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.CharField(max_length=20)),
                ('tquantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('submitted_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.item')),
            ],
        ),
    ]
